### ISSUE TITLE
milestone v1 todo

### ISSUE THREAD

**Issue by tomoyukikashiro** [tomoyukikashiro/chrome-devtools-fun#1]
## Critical
- [x] version pages and add link to nav
- [x] tag pages and link to navi
- [x] video or fn or chapter ??
- [x] footer
- [x] hero in index.html
- [x] loading
- [x] algolia
- [x] SEO
- [x] OGP
- [x] header logo link

## Chore
- [x] google analytics
- [x] edit package.json
- [x] edit gatsby-config
- [x] README
- [x] links (code, twitter)
- [x] prepare data
